# this file is for installing dependencies on the host

# sudo apt-get update: sudo apt-get install python-pip
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

# pip install -- upgrade pip
- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

# pip install openstacksdk, required for the interaction with openstack API
- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest

#pip install docker
- name: Install docker
  become: yes
  pip:
    name: ['docker']
    state: latest

# sudo apt-get install git
- name: Install git
    become: yes
    apt: 
        name: ['git'] 
        state: latest
        update_cache: yes
  when: ansible_distribution == "Ubuntu"
       
